#!/bin/sh /etc/rc.common
 
USE_PROCD=1
START=99
STOP=01

start_service() {
    procd_open_instance
    procd_set_param env TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    procd_set_param command /opt/sbin/cloudflared
    procd_append_param command --pidfile /var/run/cloudflared.pid
    procd_append_param command --logfile /var/log/cloudflared.log
    procd_append_param command tunnel
    procd_append_param command run
    procd_append_param command $HOSTNAME

    procd_set_param stdout 1
    procd_set_param stderr 1

    # respawn retry is 0 because we want to keep trying to bring cloudflared up
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-10} ${respawn_retry:-0}

    procd_close_instance
}

stop_service() {
    echo "Stop Cloudflared requested"
}
